In [1]:
import pandas as pd

In [4]:
# DataFrame Methods -> These methods help in EDA

data=pd.read_csv("employee-data.csv")

In [9]:
# 1-> .head()

data.head()        # It prints data of initial 5 Rows
data.head(2)       # If we want to print only starting 2 rows

   id      name   age country gender   income
0   1  John Doe  29.0     USA   Male  55000.0
1   1  John Doe  29.0     USA   Male  55000.0

In [10]:
# 2-> .tail()

data.tail()        # It prints data of trailing 5 Rows
data.tail(2)       # If we want to print only last 2 rows then

    id         name   age country gender   income
9    9  Carlos Ruiz   NaN  Mexico   Male  45000.0
10  10  Emily Davis  31.0     USA    NaN  58000.0

In [15]:
# 3-> .sample() 

data.sample()        # It prints any one random row

   id name   age country  gender   income
6   6  NaN  45.0   India  Female  73000.0