In [1]:
import pandas as pd

In [2]:
# DataFrame Methods -> These methods help in EDA

data=pd.read_csv("employee-data.csv")

In [3]:
# 1-> .head()

data.head()        # It prints data of initial 5 Rows
data.head(2)       # If we want to print only starting 2 rows

   id      name   age country gender   income
0   1  John Doe  29.0     USA   Male  55000.0
1   1  John Doe  29.0     USA   Male  55000.0

In [4]:
# 2-> .tail()

data.tail()        # It prints data of trailing 5 Rows
data.tail(2)       # If we want to print only last 2 rows then

    id         name   age country gender   income
9    9  Carlos Ruiz   NaN  Mexico   Male  45000.0
10  10  Emily Davis  31.0     USA    NaN  58000.0

In [5]:
# 3-> .sample() 

data.sample()        # It prints any one random row 
data.sample(4)       # It prints 4 random rows

    id         name   age country  gender   income
10  10  Emily Davis  31.0     USA     NaN  58000.0
6    6          NaN  45.0   India  Female  73000.0
8    8   Rachel Lee  29.0     USA  Female  62000.0
1    1     John Doe  29.0     USA    Male  55000.0

In [6]:
# 3-> .info() 

data.info()            # It gives summary about the Data , how many rows,columns etc etc ....

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       11 non-null     int64
 1   name     10 non-null     object
 2   age      8 non-null      float64
 3   country  10 non-null     object
 4   gender   10 non-null     object
 5   income   10 non-null     float64
dtypes: float64(2), int64(1), object(3)
memory usage: 660.0+ bytes

In [7]:
# 4-> .shape

data.shape           # It returns tupple of row and column values

(11, 6)

In [8]:
# 4-> .describe()

data.describe()       # Gives important statistics of the numerical columns

              id        age        income
count  11.000000   8.000000     10.000000
mean    5.090909  32.750000  57600.000000
std     3.176619   6.065123   8896.940798
min     1.000000  27.000000  45000.000000
25%     2.500000  29.000000  52000.000000
50%     5.000000  30.000000  56500.000000
75%     7.500000  35.000000  62000.000000
max    10.000000  45.000000  73000.000000

In [9]:
# 4-> .columns

data.columns       # It wil print the header values of all the columns

Index(['id', 'name', 'age', 'country', 'gender', 'income'], dtype='object')

In [10]:
# 4-> .nynique()

data.nunique()      # It will print the total number of unique values in a column

id         10
name        9
age         6
country     6
gender      3
income      8
dtype: int64