In [1]:
import pandas as pd

In [4]:
# Loading Titanic DataSet.

raw_data=pd.read_csv("Titanic-Dataset.csv")
raw_data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [7]:
# A=) Display only columns : Name,Sex,Age,Fare,Survived

raw_data[["Name", "Sex", "Age", "Fare", "Survived"]]

,Name,Sex,Age,Fare,Survived
0,"Braund, Mr. Owen Harris",male,22.0,7.2500,0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.2833,1
2,"Heikkinen, Miss. Laina",female,26.0,7.9250,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,53.1000,1
4,"Allen, Mr. William Henry",male,35.0,8.0500,0
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,27.0,13.0000,0
887,"Graham, Miss. Margaret Edith",female,19.0,30.0000,1
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,23.4500,0
889,"Behr, Mr. Karl Howell",male,26.0,30.0000,1
890,"Dooley, Mr. Patrick",male,32.0,7.7500,0

In [11]:
# B=) Select passengers who are : female & fare>30

raw_data.query('Sex == "female" & Fare > 30')[["Sex", "Fare"]]

        Sex      Fare
1    female   71.2833
3    female   53.1000
9    female   30.0708
25   female   31.3875
31   female  146.5208
..      ...       ...
853  female   39.4000
856  female  164.8667
863  female   69.5500
871  female   52.5542
879  female   83.1583

[113 rows x 2 columns]

In [15]:
# C=) Group by Pclass and compute:
raw_data.groupby("Pclass")

# 1-> Survival rate
raw_data.groupby("Pclass")["Survived"].mean()

# 2-> Average fare
raw_data.groupby("Pclass")["Fare"].mean()

# 3-> Average Age
raw_data.groupby("Pclass")["Age"].mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64